apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Namespace }}{{ end }}
data:
  PORT: "{{ .Values.application.port }}"
  ENVIRONMENT: "{{ .Values.application.environment }}"
  CR_NAMESPACE: "{{ .Values.operatorNamespace }}"
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Caddy Helm</title>
    </head>
    <body>
        <h1>Welcome to Caddy Helm</h1>
        <p>Team Details: ...</p>
    </body>
    </html>