apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "caddy-helm.fullname" . }}
  labels:
    {{- include "caddy-helm.labels" . | nindent 4 }}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Namespace }}{{ end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deploymentStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deploymentStrategy.rollingUpdate.maxUnavailable }}
  minReadySeconds: {{ .Values.deploymentStrategy.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.deploymentStrategy.progressDeadlineSeconds }}
  selector:
    matchLabels:
      {{- include "caddy-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "caddy-helm.labels" . | nindent 8 }}
        app : {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: topology.kubernetes.io/zone
      imagePullSecrets:
        - name: my-dockerhub-secret
      containers:
        - name: {{ .Chart.Name }}
          #image: "{{ .Values.image.repository }}:v{{ .Values.image.tag }}"
          image: peggyliao/static:latest
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.application.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.application.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: html-volume
          configMap:
            name: {{ .Release.Name }}-html
            items:
              - key: index.html
                path: index.html