apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy-helm.fullname" . }}-service
  labels:
    {{- include "caddy-helm.labels" . | nindent 4 }}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Namespace }}{{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "caddy-helm.selectorLabels" . | nindent 4 }}