# Default values for webapp-chart

namespace:
  create: false
  name: caddy-helm

# Set labels for the application

labels:
  app: caddy-helm
  chart: caddy-helm-chart
  release: caddy-helm

# Replica count for the application
replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5

# Image details for the application
image:
  repository: peggyliao/static:latest
  tag: "0.1.0"
  pullPolicy: IfNotPresent

# Service details for the application
service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true

# Target port on which the application is running
application:
  port: 8080
  environtment: dev

# Deployment strategies to be followed
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  minReadySeconds: 30
  progressDeadlineSeconds: 180

configMapName: caddy-helm-config

operatorNamespace: webapp-operator-system

resources:
  requests:
    memory: "512Mi"
    cpu: "350m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# limits
limits:
  type: container
  default:
    memory: "1Gi"
    cpu: "500m"
  defaultRequest:
    memory: "1Gi"
    cpu: "500m"
  max:
    memory: "2Gi"
    cpu: "2"
